version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: move built files to the build folder
          command: mkdir build && mv out build/
      - persist_to_workspace:
          root: build
          paths:
            - out
  deploy:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - checkout
      - attach_workspace:
          at: build
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Disable jekyll builds
          command: touch build/out/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "leo+nodemarkupci@bocoup.com"
            git config user.name "Leo Balter (Nodemarkup CI)"
      - add_ssh_keys
      - run:
          name: Keyscan Github
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy docs to gh-pages branch
          command: npm run ci-gh-pages

workflows:
  version: 2
  build_only:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
